[tools]
deno = "latest"
rust = "latest"
usage = "latest"
node = "lts"
chezmoi = "latest"
python = "latest"
java = "openjdk-25.0.0"
pnpm = "latest"
bun = "latest"
go = "latest"
sops = "latest"
age = "latest"
julia = "latest"
zig = "latest"

[env]

[settings]
idiomatic_version_file_enable_tools = ["node"]
